export const featureKeys = [
  "blogs",
  "customDomains",
  "premiumThemes",
  "watermarks",
  "clientProofing",
  "photos.total",
  "heroImages.total",
  "pageHeaderImages",
  "photos.perCategory",
  "categories.total",
  "subcategories.perCategory",
  "galleries.total",
  "photos.perGallery",
  "premiumThemes.limit",
  "themeComponents",
  "advancedCustomization",
  "anyLanguageLocalization",
  "freeMaintenance.months",
  "adminDashboard",
  "responsiveDesign",
  "categoryRequests.total"
] as const;

export type FeatureKey = (typeof featureKeys)[number];

export const defaultPlanFeatures: Record<string, Partial<Record<FeatureKey, boolean>>> = {
  free: {
    blogs: true,
    customDomains: false,
    premiumThemes: false,
    watermarks: false,
    clientProofing: false,
    "photos.total": true,
    "heroImages.total": true,
    pageHeaderImages: false,
    "photos.perCategory": true,
    "categories.total": true,
    "subcategories.perCategory": true,
    "galleries.total": true,
    "photos.perGallery": true,
    "premiumThemes.limit": false,
    themeComponents: false,
    adminDashboard: true,
    responsiveDesign: true,
    "categoryRequests.total": false
  },
  plus: {
    blogs: true,
    customDomains: true,
    premiumThemes: true,
    watermarks: false,
    clientProofing: false,
    "photos.total": true,
    "heroImages.total": true,
    pageHeaderImages: true,
    "photos.perCategory": true,
    "categories.total": true,
    "subcategories.perCategory": true,
    "galleries.total": true,
    "photos.perGallery": true,
    "premiumThemes.limit": true,
    themeComponents: true,
    advancedCustomization: false,
    anyLanguageLocalization: false,
    "freeMaintenance.months": false,
    adminDashboard: true,
    responsiveDesign: true,
    "categoryRequests.total": true
  },
  pro: {
    blogs: true,
    customDomains: true,
    premiumThemes: true,
    watermarks: true,
    clientProofing: true,
    "photos.total": true,
    "heroImages.total": true,
    pageHeaderImages: true,
    "photos.perCategory": true,
    "categories.total": true,
    "subcategories.perCategory": true,
    "galleries.total": true,
    "photos.perGallery": true,
    "premiumThemes.limit": true,
    themeComponents: true,
    advancedCustomization: false,
    anyLanguageLocalization: false,
    "freeMaintenance.months": false,
    adminDashboard: true,
    responsiveDesign: true,
    "categoryRequests.total": true
  },
  ownership: {
    blogs: true,
    customDomains: true,
    premiumThemes: true,
    watermarks: true,
    clientProofing: true,
    "photos.total": true,
    "heroImages.total": true,
    pageHeaderImages: true,
    "photos.perCategory": true,
    "categories.total": true,
    "subcategories.perCategory": true,
    "galleries.total": true,
    "photos.perGallery": true,
    "premiumThemes.limit": true,
    themeComponents: true,
    advancedCustomization: true,
    anyLanguageLocalization: true,
    "freeMaintenance.months": true,
    adminDashboard: true,
    responsiveDesign: true,
    "categoryRequests.total": true
  }
};

export function hasFeature(planKey: string, feature: FeatureKey) {
  return Boolean(defaultPlanFeatures[planKey]?.[feature]);
}
